### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 장바구니 조회(비회원 장바구니 조회 - 모든 아이템 조회)
GET http://localhost:10370/api/guest-carts

### 비회원 장바구니 수동삭제(레디스에서 자동삭제되게 하였지만 혹시나 필요할경우 사용)
DELETE http://localhost:10370/api/guest-carts

### 비회원 장바구니에 책담기(해당세션의 장바구니가 없을경우 장바구니 생성)
POST http://localhost:10370/api/guest-cart-items
Content-Type: application/json
Accept: application/json

{
  "bookId": 2,
  "quantity": 3
}

### 비회원 장바구니 책 단건조회
GET http://localhost:10370/api/guest-cart-items/2

### 비회원 장바구니 책 수량 변경
PATCH http://localhost:10370/api/guest-cart-items
Content-Type: application/json
Accept: application/json

{
  "bookId": 1,
  "quantity": 5
}

### 비회원 장바구니 책 삭제(단건 삭제)
DELETE http://localhost:10370/api/guest-cart-items/1

### 비회원 장바구니 비우기
DELETE http://localhost:10370/api/guest-cart-items