### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 카트생성(회원)
POST http://localhost:10370/api/user-carts
Accept: application/json
Content-Type: application/json
X-User-Id: 22

### 카트 조회(회원)
GET http://localhost:10370/api/user-carts
Accept: application/json
Content-Type: application/json
X-User-Id: 22

### 카트 삭제(회원)
DELETE http://localhost:10370/api/user-carts/1

### 카트 아이템 생성(회원)
POST http://localhost:10370/api/user-cart-items/1
Content-Type: application/json
Accept: application/json

{
  "bookId": 3,
  "quantity": 3
}

### 카트 아이템 조회(회원)
GET http://localhost:10370/api/user-cart-items/3

### 책 수량 변경(회원)
PATCH http://localhost:10370/api/user-cart-items/1
Content-Type: application/json
Accept: application/json

{
  "bookId": 1,
  "quantity": 5
}

### 카트 아이템 삭제(회원)
DELETE http://localhost:10370/api/user-cart-items/3

#### 카트 병합
POST http://localhost:10370/api/carts/merge
Content-Type: application/json
Accept: application/json

{
  "userId": 22
}