server:
  port: 10370
spring:
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/project_be10_team4
    username: project_be10_team4
    password: uEUklnkbk*7*_O4H
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password:
      timeout: 2000
  cloud:
    config:
      enabled: false

token:
  secret: # ~~~~~~

logging:
  level:
    com.netflix.discovery: off
    com.netflix.eureka: off
    org.springframework.cloud.netflix.eureka: off
