server:
  port: 10370

spring:
  application:
    name: cart-service
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka